# Generated by Django 5.0 on 2024-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_monitor', '0002_alter_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='api_location',
            field=models.CharField(choices=[('cloud', 'cloud'), ('cloud', 'local')], max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
