"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+74x)9m1hsf)--#99%dgeqduae6if_g&nhanbzi2brd_#$r$$i"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'https://manage.inethilocal.net', 'https://manage-backend.inethilocal.net']

CORS_ALLOW_ALL_ORIGINS = DEBUG

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'ap_monitor',
    'rest_framework',
    'corsheaders',
    'django_keycloak',
]

REST_FRAMEWORK = {
    # ... other rest framework settings.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'django_keycloak.authentication.KeycloakAuthentication'
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django_keycloak.middleware.KeycloakMiddleware',
]
AUTHENTICATION_BACKENDS = ('django_keycloak.backends.KeycloakAuthenticationBackend',)
ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'manage',
        'USER': 'inethi',
        'PASSWORD': 'iNethi2023#',
        #'HOST': '127.0.0.1', # this works when running python locally
        'HOST': 'inethi-manage-mysql',
        'PORT': '3306',
    }
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "django_keycloak.KeycloakUserAutoId"
KEYCLOAK_CONFIG = {
    # Keycloak's Public Server URL (e.g. http://localhost:8080)
    'SERVER_URL': 'https://keycloak.inethilocal.net',
    # Keycloak's Internal URL
    # (e.g. http://keycloak:8080 for a docker service named keycloak)
    # Optional: Default is SERVER_URL
    'INTERNAL_URL': 'https://keycloak.inethilocal.net',
    # Override for default Keycloak's base path
    # Default is '/auth/'

    'BASE_PATH': '/auth/',
    # The name of the Keycloak's realm


    'REALM': 'master',
    # The ID of this client in the above Keycloak realm
    'CLIENT_ID': 'backend',
    # The secret for this confidential client
    # replace with your own
    'CLIENT_SECRET_KEY': 'UrLkJ8bT2tnPKCDZZl7Ahov9XdFH1JH7',
    # The name of the admin role for the client
    'CLIENT_ADMIN_ROLE': 'admin',
    # The name of the admin role for the realm
    'REALM_ADMIN_ROLE': 'admin',
    # Regex formatted URLs to skip authentication
    'EXEMPT_URIS': [],
    # Flag if the token should be introspected or decoded (default is False)
    'DECODE_TOKEN': False,
    # Flag if the audience in the token should be verified (default is True)
    'VERIFY_AUDIENCE': True,
    # Flag if the user info has been included in the token (default is True)
    'USER_INFO_IN_TOKEN': True,
    # Flag to show the traceback of debug logs (default is False)
    'TRACE_DEBUG_LOGS': False,
    # The token prefix that is expected in Authorization header (default is 'Bearer')
    'TOKEN_PREFIX': 'Bearer'
}