# Generated by Django 5.0.6 on 2024-06-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('node_down', 'Node Down'), ('node_up', 'Node Up'), ('unknown', 'Unknown')], max_length=20)),
                ('type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('utility', 'Utility'), ('entertainment', 'Entertainment'), ('games', 'Games'), ('education', 'Education')], max_length=20)),
                ('api_location', models.CharField(choices=[('cloud', 'Cloud'), ('local', 'Local')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnknownNode',
            fields=[
                ('mac', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('from_ip', models.CharField(max_length=15)),
                ('gateway', models.IntegerField()),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=32)),
                ('created', models.DateTimeField()),
                ('cloud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.cloud')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hardware', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('config_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_contact_from_ip', models.CharField(max_length=30)),
                ('mesh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.mesh')),
                ('neighbours', models.ManyToManyField(to='monitoring.node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_total', models.IntegerField(blank=True, null=True)),
                ('mem_free', models.IntegerField(blank=True, null=True)),
                ('uptime', models.CharField(blank=True, max_length=255, null=True)),
                ('system_time', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='monitoring.node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_number', models.IntegerField()),
                ('frequency_band', models.CharField(blank=True, max_length=10, null=True)),
                ('mac', models.CharField(max_length=17)),
                ('tx_bytes', models.BigIntegerField()),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_packets', models.BigIntegerField()),
                ('rx_packets', models.BigIntegerField()),
                ('tx_bitrate', models.IntegerField()),
                ('rx_bitrate', models.IntegerField()),
                ('tx_failed', models.IntegerField()),
                ('tx_retries', models.IntegerField()),
                ('signal_now', models.IntegerField()),
                ('signal_avg', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='monitoring.node')),
            ],
        ),
        migrations.CreateModel(
            name='UptimeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_state', models.BooleanField()),
                ('state_datetime', models.DateTimeField()),
                ('report_datetime', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uptime_metrics', to='monitoring.node')),
            ],
        ),
    ]
