# Generated by Django 5.0.4 on 2024-04-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('access_point', 'Access Point'), ('firewall', 'Firewall'), ('local_server', 'Local Server'), ('dns_server', 'DNS Server'), ('global_server', 'Global Server')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('utility', 'Utility'), ('entertainment', 'Entertainment'), ('games', 'Games'), ('education', 'Education')], max_length=20)),
                ('api_location', models.CharField(choices=[('cloud', 'Cloud'), ('local', 'Local')], max_length=10)),
            ],
        ),
    ]
