# Generated by Django 5.0.6 on 2024-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uptimemetric',
            old_name='node_state',
            new_name='reachable',
        ),
        migrations.RemoveField(
            model_name='uptimemetric',
            name='report_datetime',
        ),
        migrations.RemoveField(
            model_name='uptimemetric',
            name='state_datetime',
        ),
        migrations.AddField(
            model_name='uptimemetric',
            name='loss',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uptimemetric',
            name='rtt_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uptimemetric',
            name='rtt_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uptimemetric',
            name='rtt_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uptimemetric',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
