# Generated by Django 5.0.4 on 2024-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('node_down', 'Node Down'), ('node_up', 'Node Up'), ('unknown', 'Unknown')], max_length=20)),
                ('type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], max_length=10)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
