# Generated by Django 5.0.6 on 2024-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_node_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeload',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='uptimemetric',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='node',
            name='neighbours',
            field=models.ManyToManyField(blank=True, to='monitoring.node'),
        ),
    ]
