# Generated by Django 5.0 on 2024-04-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_monitor', '0003_alter_service_api_location_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='api_location',
            field=models.CharField(choices=[('cloud', 'cloud'), ('local', 'local')], max_length=10),
        ),
    ]
